version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - checkout
      - run:
          name: build binary
          command: make build-linux
      - run:
          name: start  webserver
          command: ./httpGO
          background: true
      - run: 
          name: test version endpoint
          command: curl localhost:8000/version | grep $CIRCLE_SHA
