version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - checkout
      - run: make build-linux
      - run:
          name: test webserver
          command: ./httpGO
          background: true
      - run: curl localhost:8000/version | grep $CIRCLE_SHA1
      # background: true
