version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /src
    steps:
      - checkout
      - run:
          name: build binary
          command: |
            make build-linux && ./httpGO