version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - checkout
      - run:
          name: build binary
          command: make build-linux
      - run:
          name: start  webserver
          command: ./httpGO
          background: true
      - run: 
          name: test version endpoint
          command: curl localhost:8000/version | grep $CIRCLE_SHA1
      # if we can compile & run the webserver
      # we'll move the binary downstream
      - persist_to_workspace:
          root: /go/src/github.com/aedifex/
          paths:
            - httpGo

  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - run: echo "hello from test"
      - attach_workspace:
          at: /go/src/github.com/aedifex/
      - run: ls -alt

workflows:
  version: 2
  # arbitrary workflow name...
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build