version: 2
jobs:
  build-binary:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - checkout
      - run:
          name: build binary
          command: make build-linux