version: 2
jobs:
  build-binary:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - checkout
      - run:
          name: build binary
          command: make build-linux
      - run:
          name: start  webserver
          command: ./httpGo
          background: true
      - run:
          name: test version endpoint
          command: |
            curl localhost:8000/version | grep $CIRCLE_SHA1
      # If we can successfully compile and execute the binary,
      # the 'build-binary' job will complete and we'll pass the artifact
      # downstream via Workspaces.
      - persist_to_workspace:
          root: /go/src/github.com/aedifex/
          paths:
            - httpGo
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/aedifex/httpGo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/aedifex/
      - run: make build-docker-image
workflows:
  version: 2
  # arbitrary workflow name...
  build-test-deploy:
    jobs:
      - build-binary
      - test:
          requires:
            - build-binary