pipeline:
  name: Build GOSST
  identifier: Build_aedifex_GOSST_1720712593403
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Artifact
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Azure Login
                  identifier: Azure_Login
                  spec:
                    shell: Sh
                    command: |-
                      export AZURE_CLIENT_ID="<+secrets.getValue('AZURE_CLIENT_ID')>"

                      echo ${AZURE_CLIENT_ID}
                contextType: Pipeline
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      git status
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1720712508026
                    repoName: aedifex/GOSST
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: Run
                  name: Compile Binary
                  identifier: Compile_Binary
                  spec:
                    shell: Bash
                    command: |-
                      export COMMIT_SHA="<+codebase.commitSha>"

                      make build

                      make docker-build
              - step:
                  type: BuildAndPushACR
                  name: Build Image and Push to ACR
                  identifier: Build_Image_and_Push_to_ACR
                  spec:
                    connectorRef: account.Azure_Aedifex_Sandbox
                    repository: ghosst.azurecr.io/gosst
                    tags:
                      - hopeful
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712508026
        repoName: aedifex/GOSST
        build: <+input>
