pipeline:
  name: Build GOSST - deploy to ACA
  identifier: Build_aedifex_GOSST_1720712593403
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Artifact
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Test
                  name: Execute Tests
                  identifier: Execute_Tests
                  spec:
                    shell: Sh
                    command: |-
                      go install github.com/jstemmer/go-junit-report/v2@latest

                      make test \
                        COMMIT_SHA="<+codebase.commitSha>" \
                        GIT_BRANCH="<+codebase.branch>" \
                        BUILD_TIME="$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
                        DEPLOYED_BY="<+pipeline.triggeredBy.email>" \
                        BUILD_ID="<+pipeline.sequenceId>"

                      cat report.out | $HOME/go/bin/go-junit-report -set-exit-code > report.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - report.xml
                    intelligenceMode: true
              - step:
                  type: Run
                  name: Compile Binary
                  identifier: Compile_Binary
                  spec:
                    shell: Bash
                    command: |-
                      export COMMIT_SHA="<+codebase.commitSha>"
                      export DEPLOYED_BY="<+pipeline.triggeredBy.email>"

                      make build \
                        COMMIT_SHA="<+codebase.commitSha>" \
                        GIT_BRANCH="<+codebase.branch>" \
                        BUILD_TIME="$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
                        DEPLOYED_BY="<+pipeline.triggeredBy.email>" \
                        BUILD_ID="<+pipeline.sequenceId>"
              - step:
                  type: BuildAndPushACR
                  name: Build Image and Push to ACR
                  identifier: Build_Image_and_Push_to_ACR
                  spec:
                    connectorRef: account.Azure_Aedifex_Sandbox
                    repository: gosst.azurecr.io/gosst
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
                  when:
                    stageStatus: Success
              - step:
                  type: Run
                  name: Save Image as TAR
                  identifier: Save_Image_as_TAR
                  spec:
                    shell: Sh
                    command: |-
                      docker build -t gosst:<+pipeline.sequenceId> .
                      docker save -o alpine.tar gosst:<+pipeline.sequenceId>

                      tar -tvf alpine.tar | head

                      touch /harness/hello.txt
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_1
                  identifier: AquaTrivy_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      workspace: /harness/alpine.tar
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: local_archive
                      tag: <+pipeline.sequenceId>
                      name: ghosst.azurecr.io/gosst
                  when:
                    stageStatus: Success
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
    - stage:
        name: Deploy Artifact
        identifier: Deploy_Artifact
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: false
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Update ACA
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

                      az login --service-principal \
                        --username '<+secrets.getValue("account.AzureServiceAcct")>' \
                        --password '<+secrets.getValue("account.Azure_Sandbox")>' \
                        --tenant "1ab56db7-740b-4932-a1cb-db5d0b9e945e"

                      az extension add --name containerapp

                      az containerapp update \
                        --name gosst-app \
                        --resource-group gosst \
                        --image gosst.azurecr.io/gosst:<+pipeline.sequenceId>
              - parallel:
                  - step:
                      type: Run
                      name: Verify Deployment
                      identifier: Verify_Deployment
                      spec:
                        shell: Bash
                        command: |-
                          FQDN=$(az containerapp show \
                                    --name gosst-app \
                                    --resource-group gosst \
                                    --query properties.configuration.ingress.fqdn \
                                    -o tsv)

                          echo "FQDN=$FQDN"
                          echo "FQDN=$FQDN" >> output.env
                      outputVariables:
                        - name: FQDN
                  - step:
                      type: Run
                      name: Slack Notification to Service Owner
                      identifier: Slack_Notification_to_Service_Owner
                      spec:
                        shell: Sh
                        command: |-
                          SLACK_URL=$(echo "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzUFM2UkdEVEsvQjA4RzY3TjZWUlUvNElpZVdYdVJia1NRNEhSNlJCdVNVOE44" | base64 -d)

                          curl -X POST -H "Content-Type: application/json" -d '{
                            "text": "*Deployment Notification* 🚀\nPipeline: `<+pipeline.identifier>`\nExecution ID: `<+pipeline.executionId>`\nStatus: `<+pipeline.status>`\nTriggered By: `<+pipeline.triggeredBy.email>`\nTriggered At: `<+pipeline.startTs>`\nPipeline URL: <+pipeline.executionUrl>\n\n*Service URL:* <https://gosst-app.redbeach-63fd196a.westus.azurecontainerapps.io|Open App>"
                          }' "$SLACK_URL"
          buildIntelligence:
            enabled: false
        variables:
          - name: DOCKER_PASSWORD
            type: Secret
            description: ""
            required: false
            value: account.Dockerhub_Password
        when:
          pipelineStatus: Success
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712508026
        repoName: aedifex/GOSST
        build: <+input>
  tags: {}
