pipeline:
  name: Build GOSST
  identifier: Build_aedifex_GOSST_1720712593403
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Artifact
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      git status
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1720712508026
                    repoName: aedifex/GOSST
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: Run
                  name: Check dir contents
                  identifier: Check_dir_contents
                  spec:
                    shell: Sh
                    command: ls -alt
              - step:
                  type: Run
                  name: Compile Binary
                  identifier: Compile_Binary
                  spec:
                    shell: Sh
                    command: GOOS=linux GOARCH=amd64 go build -o main_linux .
              - step:
                  type: Run
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    shell: Sh
                    command: docker build --platform linux/amd64 -t ghosst.azurecr.io/gosst:latest .
              - step:
                  type: BuildAndPushACR
                  name: Push to ACR
                  identifier: Push_to_ACR
                  spec:
                    connectorRef: account.Azure_Aedifex_Sandbox
                    repository: ghosst.azurecr.io/gosst
                    tags:
                      - harness
                    caching: true
                    buildArgs:
                      platform: linux/amd64
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712508026
        repoName: aedifex/GOSST
        build: <+input>
